version: 2
jobs:
  build:
    machine:
      docker_layer_caching: false
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t asrob/ubuntu-nginx:1.17.0 .
      - run: docker push asrob/ubuntu-nginx:1.17.0
